networks:
  default:
    external: true
    name: roboshop
services:
  mongodb: 
    image: mongodb:1
    container_name: mongodb:1

  catalogue:
    image: catalogue:1
    depends_on:
    - mongodb
    container_name: catalogue:1

  web:
    image: web:1
    container_name: web:1
    ports:
    - "80:80"
    depends_on:
    - catalogue

  redis:
    image: redis
    container_name: redis:1

  user:
    image: user:1
    container_name: user:1
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:1
    container_name: cart:1
    depends_on:
    - redis
    - catalogue  
  mysql:
    image: mysql:1
    container_name: mysql:1

  shipping:
    image: shipping:1
    container_name: shipping:1
    depends_on:
    - mysql  







