networks:
  default:
    external: true
    name: roboshop
volumes:
  mongodb:
  redis:
  mysql:


services:
  mongodb: 
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume

  catalogue:
    image: catalogue:v1
    depends_on:
    - mongodb
    container_name: catalogue

  web:
    image: web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue

  redis:
    image: redis
    container_name: redis
    volumes:
    - source: mongodb
      target: /data
      type: volume

  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue

  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - source: mongodb
      target: /var/lib/mysql
      type: volume

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql  







